//package bzu.comp438.qa.selenium;// Generated by Selenium IDE
//
//import com.aventstack.extentreports.ExtentReports;
//import com.aventstack.extentreports.ExtentTest;
//import com.aventstack.extentreports.reporter.ExtentSparkReporter;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import org.junit.jupiter.api.TestInstance;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.support.ui.Select;
//
//import java.util.*;
//@TestInstance(TestInstance.Lifecycle.PER_CLASS)
//
//public class ExtentReportsTests {
//    private WebDriver driver;
//    private Map<String, Object> vars;
//    JavascriptExecutor js;
//    private ExtentSparkReporter sparkReporter;
//    private ExtentReports extent;
//
//
//
//
//
//    @Before
//    public void setUp() {
//        System.setProperty("webdriver.gecko.driver", "/usr/local/bin/geckodriver");
//        driver = new FirefoxDriver();
//        js = (JavascriptExecutor) driver;
//        vars = new HashMap<String, Object>();
//
//
//        // Initialize the HtmlReporter
////        sparkReporter = new ExtentSparkReporter( "/home/sc/testReport.html");
//
//        // Initialize ExtentReports and attach the HtmlReporter
//        extent = new ExtentReports();
////        extent.attachReporter(sparkReporter);
//
//        // Creating tests
////        test = extent.createTest("testOne", "Sample description of the test being performed");
//    }
//
//    @After
//    public void tearDown() {
//        driver.quit();
//        // writing everything to document
//        extent.flush();
//    }
//
//    @Test
//    public void testOne() {
//
//        // Initialize the HtmlReporter
//        sparkReporter = new ExtentSparkReporter( "/home/sc/testReport1.html");
//        ExtentTest test = extent.createTest("testOne", "Sample description of the test being performed");
//        extent.attachReporter(sparkReporter);
//
//        test.assignCategory("p1");
//        test.info("Starting testOne");
//
//        test.info("Opening URL: http://127.0.0.1:5500/client/index.html");
//        driver.get("http://127.0.0.1:5500/client/index.html");
////========================================================================
//        // Step 2: Set Window Size
//        test.info("Setting window size to 919x698");
//        driver.manage().window().setSize(new Dimension(919, 698));
////========================================================================
//
//        // Step 3: Click on 'amount'
//        test.info("Clicking on the 'amount' field");
//        driver.findElement(By.id("amount")).click();
////========================================================================
//
//        // Step 4: Type '100' in 'amount'
//        test.info("Typing '100' in the 'amount' field");
//        driver.findElement(By.id("amount")).sendKeys("100");
////========================================================================
//
//        test.info("Selecting 'fromCurrency' dropdown menu");
//        // Steps 6-9: Selecting currency in 'fromCurrency'
//        WebElement fromCurrencyDropdown = driver.findElement(By.id("fromCurrency"));
//        fromCurrencyDropdown.click(); // Open the dropdown
//
//        test.info("Selecting 'TND' in 'fromCurrency'");
//        Select fromCurrencySelect = new Select(fromCurrencyDropdown);
//        fromCurrencySelect.selectByVisibleText("TND"); // Select the option
////========================================================================
//
//
//        test.info("Selecting 'toCurrency' dropdown menu");
//        // Steps 6-9: Selecting currency in 'fromCurrency'
//        WebElement toCurrencyDropdown = driver.findElement(By.id("toCurrency"));
//        toCurrencyDropdown.click(); // Open the dropdown
//
//        test.info("Selecting 'BZD' in 'toCurrency'");
//        Select toCurrencySelect = new Select(toCurrencyDropdown);
//        toCurrencySelect.selectByVisibleText("BZD"); // Select the option
////========================================================================
//
//        // Step 20: Click on the 'btn-cov' button
//        test.info("Clicking on the 'btn-cov' button");
//        driver.findElement(By.id("btn-cov")).click();
//
//
//        test.info("Displaying Error Pop Up");
//
//    }
//
//    @Test
//    public void testTwo () {
//        sparkReporter = new ExtentSparkReporter( "/home/sc/testReport2.html");
//        ExtentTest test = extent.createTest("testTwo", "Sample description of the test being performed");
//        test.assignCategory("p2");
//        extent.attachReporter(sparkReporter);
//        test.info("Starting testTwo");
//
//        test.info("Opening URL: http://127.0.0.1:5500/client/index.html");
//        driver.get("http://127.0.0.1:5500/client/index.html");
////========================================================================
//        // Step 2: Set Window Size
//        test.info("Setting window size to 919x698");
//        driver.manage().window().setSize(new Dimension(919, 698));
////========================================================================
//
//        // Step 3: Click on 'amount'
//        test.info("Clicking on the 'amount' field");
//        driver.findElement(By.id("amount")).click();
////========================================================================
//
//        // Step 4: Type '100' in 'amount'
//        test.info("Typing '100' in the 'amount' field");
//        driver.findElement(By.id("amount")).sendKeys("100");
////========================================================================
//
//        test.info("Selecting 'fromCurrency' dropdown menu");
//        // Steps 6-9: Selecting currency in 'fromCurrency'
//        WebElement fromCurrencyDropdown = driver.findElement(By.id("fromCurrency"));
//        fromCurrencyDropdown.click(); // Open the dropdown
//
//        test.info("Selecting 'USD' in 'fromCurrency'");
//        Select fromCurrencySelect = new Select(fromCurrencyDropdown);
//        fromCurrencySelect.selectByVisibleText("USD"); // Select the option
////========================================================================
//
//
//        test.info("Selecting 'toCurrency' dropdown menu");
//        // Steps 6-9: Selecting currency in 'fromCurrency'
//        WebElement toCurrencyDropdown = driver.findElement(By.id("toCurrency"));
//        toCurrencyDropdown.click(); // Open the dropdown
//
//        test.info("Selecting 'ILS' in 'toCurrency'");
//        Select toCurrencySelect = new Select(toCurrencyDropdown);
//        toCurrencySelect.selectByVisibleText("ILS"); // Select the option
////========================================================================
//
//        // Step 20: Click on the 'btn-cov' button
//        test.info("Clicking on the 'btn-cov' button");
//        driver.findElement(By.id("btn-cov")).click();
//
//    }
//
//    @Test
//    public void testThree () {
//
//        sparkReporter = new ExtentSparkReporter( "/home/sc/testReport3.html");
//
//        ExtentTest test = extent.createTest("testThree", "Sample description of the test being performed");
//        test.assignCategory("p3");
//        extent.attachReporter(sparkReporter);
//        test.info("Starting testThree");
//
//        test.info("Opening URL: http://127.0.0.1:5500/client/index.html");
//        driver.get("http://127.0.0.1:5500/client/index.html");
////========================================================================
//        // Step 2: Set Window Size
//        test.info("Setting window size to 919x698");
//        driver.manage().window().setSize(new Dimension(919, 698));
////========================================================================
//
//        // Step 3: Click on 'amount'
//        test.info("Clicking on the 'amount' field");
//        driver.findElement(By.id("amount")).click();
////========================================================================
//
//        // Step 4: Type '-12.345' in 'amount'
//        test.info("Typing '-12.345' in the 'amount' field");
//        driver.findElement(By.id("amount")).sendKeys("-12.345");
//
//        test.info("a pop-up appears and alert user with input validation as : (use . or , for decimals) and you can't use negative values ex. -1.234");
//
//        driver.findElement(By.id("amount")).sendKeys("-12.345");
//        driver.findElement(By.id("amount")).clear();
//
//        driver.findElement(By.id("amount")).sendKeys("testing the input with text");
//
//        test.info("a pop-up appears and alert user with input validation as :Please use proper input");
//
////========================================================================
//
//        // Step 20: Click on the 'btn-cov' button
//        test.info("Clicking on the 'btn-cov' button");
//        test.info("a pop-up appears and alert user with input validation");
//    }
//
//}

package bzu.comp438.qa.selenium;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;
import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;

import java.util.*;



@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class ExtentReportsTests {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private ExtentSparkReporter sparkReporter;
    private ExtentReports extent;


        @BeforeAll
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "/usr/local/bin/geckodriver");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

        sparkReporter = new ExtentSparkReporter( "/home/sc/testReport.html");

        // Initialize ExtentReports and attach the HtmlReporter
        extent = new ExtentReports();
            extent.attachReporter(sparkReporter);

        // Creating tests
//        test = extent.createTest("testOne", "Sample description of the test being performed");
    }

    @AfterAll
    public void tearDown() {
        driver.quit();
        // writing everything to document
        extent.flush();
    }

    @Test
    public void testOne() {

        // Initialize the HtmlReporter
//        sparkReporter = new ExtentSparkReporter( "/home/sc/testReport1.html");
        ExtentTest test = extent.createTest("testOne", "Sample description of the test being performed");
        extent.attachReporter(sparkReporter);

        test.assignCategory("p1");
        test.info("Starting testOne");

        test.info("Opening URL: http://127.0.0.1:5500/client/index.html");
        driver.get("http://127.0.0.1:5500/client/index.html");
//========================================================================
        // Step 2: Set Window Size
        test.info("Setting window size to 919x698");
        driver.manage().window().setSize(new Dimension(919, 698));
//========================================================================

        // Step 3: Click on 'amount'
        test.info("Clicking on the 'amount' field");
        driver.findElement(By.id("amount")).click();
//========================================================================

        // Step 4: Type '100' in 'amount'
        test.info("Typing '100' in the 'amount' field");
        driver.findElement(By.id("amount")).sendKeys("100");
//========================================================================

        test.info("Selecting 'fromCurrency' dropdown menu");
        // Steps 6-9: Selecting currency in 'fromCurrency'
        WebElement fromCurrencyDropdown = driver.findElement(By.id("fromCurrency"));
        fromCurrencyDropdown.click(); // Open the dropdown

        test.info("Selecting 'TND' in 'fromCurrency'");
        Select fromCurrencySelect = new Select(fromCurrencyDropdown);
        fromCurrencySelect.selectByVisibleText("TND"); // Select the option
//========================================================================


        test.info("Selecting 'toCurrency' dropdown menu");
        // Steps 6-9: Selecting currency in 'fromCurrency'
        WebElement toCurrencyDropdown = driver.findElement(By.id("toCurrency"));
        toCurrencyDropdown.click(); // Open the dropdown

        test.info("Selecting 'BZD' in 'toCurrency'");
        Select toCurrencySelect = new Select(toCurrencyDropdown);
        toCurrencySelect.selectByVisibleText("BZD"); // Select the option
//========================================================================

        // Step 20: Click on the 'btn-cov' button
        test.info("Clicking on the 'btn-cov' button");
        driver.findElement(By.id("btn-cov")).click();


        test.info("Displaying Error Pop Up");

    }

    @Test
    public void testTwo () {
//        sparkReporter = new ExtentSparkReporter( "/home/sc/testReport2.html");
        ExtentTest test = extent.createTest("testTwo", "Sample description of the test being performed");
        test.assignCategory("p2");
        extent.attachReporter(sparkReporter);
        test.info("Starting testTwo");

        test.info("Opening URL: http://127.0.0.1:5500/client/index.html");
        driver.get("http://127.0.0.1:5500/client/index.html");
//========================================================================
        // Step 2: Set Window Size
        test.info("Setting window size to 919x698");
        driver.manage().window().setSize(new Dimension(919, 698));
//========================================================================

        // Step 3: Click on 'amount'
        test.info("Clicking on the 'amount' field");
        driver.findElement(By.id("amount")).click();
//========================================================================

        // Step 4: Type '100' in 'amount'
        test.info("Typing '100' in the 'amount' field");
        driver.findElement(By.id("amount")).sendKeys("100");
//========================================================================

        test.info("Selecting 'fromCurrency' dropdown menu");
        // Steps 6-9: Selecting currency in 'fromCurrency'
        WebElement fromCurrencyDropdown = driver.findElement(By.id("fromCurrency"));
        fromCurrencyDropdown.click(); // Open the dropdown

        test.info("Selecting 'USD' in 'fromCurrency'");
        Select fromCurrencySelect = new Select(fromCurrencyDropdown);
        fromCurrencySelect.selectByVisibleText("USD"); // Select the option
//========================================================================


        test.info("Selecting 'toCurrency' dropdown menu");
        // Steps 6-9: Selecting currency in 'fromCurrency'
        WebElement toCurrencyDropdown = driver.findElement(By.id("toCurrency"));
        toCurrencyDropdown.click(); // Open the dropdown

        test.info("Selecting 'ILS' in 'toCurrency'");
        Select toCurrencySelect = new Select(toCurrencyDropdown);
        toCurrencySelect.selectByVisibleText("ILS"); // Select the option
//========================================================================

        // Step 20: Click on the 'btn-cov' button
        test.info("Clicking on the 'btn-cov' button");
        driver.findElement(By.id("btn-cov")).click();

    }

    @Test
    public void testThree () {

//        sparkReporter = new ExtentSparkReporter( "/home/sc/testReport3.html");

        ExtentTest test = extent.createTest("testThree", "Sample description of the test being performed");
        test.assignCategory("p3");
        extent.attachReporter(sparkReporter);
        test.info("Starting testThree");

        test.info("Opening URL: http://127.0.0.1:5500/client/index.html");
        driver.get("http://127.0.0.1:5500/client/index.html");
//========================================================================
        // Step 2: Set Window Size
        test.info("Setting window size to 919x698");
        driver.manage().window().setSize(new Dimension(919, 698));
//========================================================================

        // Step 3: Click on 'amount'
        test.info("Clicking on the 'amount' field");
        driver.findElement(By.id("amount")).click();
//========================================================================

        // Step 4: Type '-12.345' in 'amount'
        test.info("Typing '-12.345' in the 'amount' field");
        driver.findElement(By.id("amount")).sendKeys("-12.345");

        test.info("a pop-up appears and alert user with input validation as : (use . or , for decimals) and you can't use negative values ex. -1.234");

        driver.findElement(By.id("amount")).sendKeys("-12.345");
        driver.findElement(By.id("amount")).clear();

        driver.findElement(By.id("amount")).sendKeys("testing the input with text");

        test.info("a pop-up appears and alert user with input validation as :Please use proper input");

//========================================================================

        // Step 20: Click on the 'btn-cov' button
        test.info("Clicking on the 'btn-cov' button");
        test.info("a pop-up appears and alert user with input validation");
    }

}

